heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  id: elastic-stack-https
  name: "Elastic Stack HTTPS"
  urls:
    - https://elasticsearch01:9200
    - https://elasticsearch02:9200
    - https://elasticsearch03:9200
    - https://kibana:5601
  username: elastic
  password: "${ES_PWD}"
  ssl:
    certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

- type: icmp
  schedule: '@every 5s'
  id: elastic-stack-ping
  name: "Elastic Stack Ping"
  hosts:
    - elasticsearch01
    - elasticsearch02
    - elasticsearch03
    - kibana

processors:
- add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    hosts: ${ELASTICSEARCH_HOSTS}
    username: elastic
    password: "${ES_PWD}"
    ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

output.elasticsearch:
  hosts: ${ELASTICSEARCH_HOSTS}
  username: elastic
  password: "${ES_PWD}"
  ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]